version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.4
    commands:
      - composer install
      - npm install
  build:
    commands:
      - npm run prod
      - npm run prod
artifacts:
  files: '**/*'
  name: exposure-$(date +%Y-%m-%d)
